---
# For use by Role Types
# Do not touch these
# CARMINE NOTE: i have no cluegi what the helly this is we should probably leave this as-is for now - Ghost

- type: roleType
  id: Neutral
  name: role-type-crew-aligned-name
  color: '#eeeeee'

- type: roleType
  id: SoloAntagonist
  name: role-type-solo-antagonist-name
  color: '#d82000'

- type: roleType
  id: Familiar
  name: role-type-familiar-name
  color: '#6495ed'

- type: roleType
  id: Silicon
  name: role-type-silicon-name
  color: '#6495ed'
