- type: entity
  id: BaseMindRole
  name: Mind Role
  description: Mind Role entity
  abstract: true
  components:
  - type: MindRole

- type: entity
  parent: BaseMindRole
  id: BaseMindRoleAntag
  abstract: true
  components:
  - type: MindRole
    antag: true

#Observer
- type: entity
  parent: BaseMindRole
  id: MindRoleObserver
  name: Observer Role
  components:
  - type: ObserverRole

#Ghost Roles
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleNeutral
  name: Ghost Role
  components:
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleFamiliar
  name: Ghost Role (Familiar)
  components:
  - type: MindRole
    roleType: Familiar
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleSilicon
  name: Ghost Role (Silicon)
  components:
  - type: MindRole
    roleType: Silicon
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleSoloAntagonist
  name: Ghost Role (Solo Antagonist)
  components:
  - type: MindRole
    roleType: SoloAntagonist
  - type: GhostRoleMarkerRole

# The Job MindRole holds the mob's Job prototype
- type: entity
  parent: BaseMindRole
  id: MindRoleJob
  name: Job Role
#  description:
  # MindRoleComponent.JobPrototype is filled by SharedJobSystem

# Silicon
- type: entity
  parent: BaseMindRole
  id: MindRoleSiliconBrain
  name: Borg Brain Role
  components:
  - type: MindRole
    roleType: Silicon
  - type: SiliconBrainRole

# goob edit - antags
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: SoloAntagonist
  - type: ChangelingRole